Converted to V3, added VX1000 layer update action
bitfocus/companion-module-novastar-controller pull request #33
Opened 2023-03-23 23:46 UTC by cyberblaststudios

- Added VX1000 Layer Update action, which allows for layer configuration and PIP functionality on the VX1000 device.
- Converted the module to Companion V3.0

2023-03-31 17:25 UTC, dnmeid requested changes
I've put some comments to the files and code. Please also check formatting, there is inconsistent use of semicolons. Add newline to end of files as well.

2023-03-31 17:25 UTC, dnmeid commented on package.json
Many of the properties can be stripped out of package.json. They should only be defined in one place (single point of truth).

2023-03-31 17:25 UTC, dnmeid commented on package.json
> +		"yarn": "^1.22.19"
Why is yarn a dependency? I don't see where the module uses yarn.

2023-03-31 17:25 UTC, dnmeid commented on config.js
suggest to rename this file to choices.js

2023-03-31 17:25 UTC, dnmeid commented on actions.js
> +	initialXBuffer.writeInt32LE(initialX)
write will fail if initialX is no integer in valid range. You should round it to integer here and clamp the range in the action option.
Same for the other buffer assignments.

2023-03-31 17:25 UTC, dnmeid commented on actions.js
> +				var cmd = Buffer.from([0x55,0xAA,0x00,0x00,0xFE,0x00,0x00,0x00,0x00,0x00,0x01,0x00,0x2D,0x00,0x00,0x13,0x01,0x00,0x00,0x95,0x56]);
use let or const instead of var

2023-04-01 19:17 UTC, cyberblaststudios commented
@dnmeid made the requested changes, but I will need to test it on the VX1000 first before merging. I will let you know when I have tested. I'll reply to the requested changes where I have questions.

2023-04-01 19:19 UTC, cyberblaststudios commented on package.json
@dnmeid I committed a change where I have removed most of the duplication. Not sure what all is required to be in the package.json file. I did keep the version, api_version, dependencies, etc. in the package.json file. Not sure if these can just be in the manifest. But I did clean it up quite a bit.

2023-04-01 19:20 UTC, cyberblaststudios commented
> I've put some comments to the files and code. Please also check formatting, there is inconsistent use of semicolons. Add newline to end of files as well.

I also added prettier formatting to this module and formatted every file but choices.js accordingly.

2023-04-02 16:37 UTC, cyberblaststudios commented
@dnmeid  Was at church this morning and tested on the VX1000, and we should be good to go except for my one question about the package.json.

2023-04-05 19:05 UTC, dnmeid commented on package.json
only the properties needed by yarn are mandatory in the package.json, so api_version could also be omitted, but it is not a big problem if this is still there atm and is removed in a later update

2023-04-05 19:18 UTC, dnmeid requested changes

2023-04-05 19:18 UTC, dnmeid commented on package.json
> +	"version": "2.0.0",
name is mandatory and can't be omitted
```suggestion
       "name": "novastar-controller",
	"version": "2.0.0",
```

2023-05-05 11:06 UTC, merged